version: '3.8'

services:
  # 1. The Database
  postgres:
    image: postgres:15
    container_name: greenpage_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenpage
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. The Queue
  redis:
    image: redis:alpine
    container_name: greenpage_queue
    ports:
      - "6379:6379"

volumes:
  postgres_data: